// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentForm.Core.Entities
{
    public partial class StudentTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? RollNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public bool? IsDeleted { get; set; }
    }
}